In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
dataset = pd.read_csv("diabetes.csv")
print (dataset.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   
2            0      145              0              0        0  44.2   
3            0      135             68             42      250  42.3   
4            1      139             62             41      480  40.7   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0  
2                     0.630   31        1  
3                     0.365   24        1  
4                     0.536   21        0  


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [4]:
df = pd.DataFrame(dataset)

le = preprocessing.LabelEncoder()
df = df.apply(le.fit_transform)

print(df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            2       76             16             28        0  120   
1            0       22             28             24       78  166   
2            0       83              0              0        0  212   
3            0       73             20             35      134  199   
4            1       77             16             34      172  188   

   DiabetesPedigreeFunction  Age  Outcome  
0                        18   26        1  
1                       102    2        0  
2                       343   10        1  
3                       203    3        1  
4                       298    0        0  


In [5]:
X = df.iloc[:, 1:10]
y = df.iloc[:, 0]
y = y.values
print(X.shape)

print(y)

(2000, 8)
[2 0 0 ... 6 0 2]


In [6]:
print('X before scaling,', X)
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.fit_transform(X)
print('X After Scaling', X_scaled)

X before scaling,       Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0          76             16             28        0  120   
1          22             28             24       78  166   
2          83              0              0        0  212   
3          73             20             35      134  199   
4          77             16             34      172  188   
...       ...            ...            ...      ...  ...   
1995       13             17             17       27   89   
1996      117             22             35       83  113   
1997       23             26              0        0  102   
1998       67             44             39       83  245   
1999       19             22              8       46   93   

      DiabetesPedigreeFunction  Age  Outcome  
0                           18   26        1  
1                          102    2        0  
2                          343   10        1  
3                          203    3        1  
4             

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2)

In [8]:
#Mengaktifkan fungsi classifier untuk KNN
model = KNeighborsClassifier (n_neighbors=4)
#Memasukkan data training pada fungsi untuk KNN
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [9]:
y_pred = model.predict (X_test)
y_pred

array([ 0,  0,  1,  1,  1,  4,  0,  4,  3,  0,  0,  6,  0,  1,  1,  1,  5,
        5, 10,  7,  6,  0,  0,  5,  7,  8,  3,  7,  8,  1,  3,  5,  4,  2,
        3,  0,  9,  1,  4,  6,  0,  4,  6,  1,  0,  1,  4,  1,  1,  2,  4,
        3,  3,  0,  1,  1,  0,  7,  6, 10,  6,  2,  1,  8,  6,  1,  2,  0,
        1,  0,  7,  2,  2,  4,  2, 12,  7,  5,  1,  3,  7,  2,  0, 12,  1,
        1,  1,  6,  0,  0,  2,  1,  1,  1,  0,  1,  0,  0,  4,  5,  0,  3,
        4,  4,  1,  1,  0,  1,  2,  9,  9,  4,  2,  8,  0,  2,  0,  7,  0,
        8,  0,  1,  9,  2,  0,  0,  2,  8, 11,  4,  3,  0,  7,  3,  4,  0,
        5,  7,  3,  0,  3,  7,  4,  2,  1,  7,  1,  8,  2,  5,  7,  0, 12,
        2,  4,  1,  2,  4,  1,  0,  1,  0,  1,  1,  1,  1, 13,  1,  7,  3,
        8,  3,  4,  7,  0,  7,  1,  7,  0,  0,  4, 12,  7,  5,  5,  0,  0,
        0,  3,  1,  3,  4,  7,  1,  0,  7,  0,  5,  2,  1,  3,  5,  1,  1,
        1,  0,  0,  3,  4,  1,  2,  7,  1,  1,  0,  1,  9,  2,  2,  1,  0,
        3,  8, 13,  3,  0

In [10]:
#Menentukan probabilitas prediksi
model.predict_proba(X_test)

array([[1.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.75, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.5 , 0.5 , ..., 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ]])

In [11]:
# Import package untuk melihat keakuratan data prediksi dengan data aktual
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
# Menampilkan matriks hasil prediksi
print(confusion_matrix(y_test, y_pred))

[[42  7  1  2  0  2  1  4  0  0  0  0  0  0]
 [13 48  5  4  1  4  0  2  0  3  0  0  1  0]
 [12 16 22  1  5  0  0  1  0  0  1  0  1  0]
 [ 6  8  2 18  0  2  1  0  0  1  0  0  0  0]
 [ 5  3  7  4 16  2  2  0  0  0  2  0  0  0]
 [ 0  3  2  1  3  8  1  1  1  0  0  0  0  1]
 [ 2  8  0  1  2  3  8  0  0  0  0  0  0  0]
 [ 2  2  0  3  2  2  3  4  1  0  0  0  1  0]
 [ 0  1  0  1  1  2  0  5  8  0  0  0  2  0]
 [ 0  0  0  1  2  0  0  7  3  2  0  0  0  0]
 [ 0  1  1  0  0  1  0  6  0  0  1  0  0  0]
 [ 0  1  0  0  1  0  0  1  0  1  1  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  2  1  0  0  0  0  0  0  1]]


In [13]:
# Ketepatan hasil prediksi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.71      0.60        59
           1       0.49      0.59      0.54        81
           2       0.55      0.37      0.44        59
           3       0.50      0.47      0.49        38
           4       0.47      0.39      0.43        41
           5       0.29      0.38      0.33        21
           6       0.47      0.33      0.39        24
           7       0.13      0.20      0.16        20
           8       0.62      0.40      0.48        20
           9       0.29      0.13      0.18        15
          10       0.20      0.10      0.13        10
          11       1.00      0.17      0.29         6
          12       0.17      0.50      0.25         2
          13       0.50      0.25      0.33         4

    accuracy                           0.45       400
   macro avg       0.44      0.36      0.36       400
weighted avg       0.47      0.45      0.44       400

